In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#data 1

f = open("./Statistics1-data/correlation1.txt", "r")
lines = f.readlines()
f.close()

x = []
y = []

for line in lines:
    (now_x, now_y) = line.replace("\n", "").split(",")
    x.append(float(now_x))
    y.append(float(now_y))

In [3]:
np.corrcoef(x, y)

array([[1.        , 0.70301706],
       [0.70301706, 1.        ]])

In [4]:
# 0.70301706

In [5]:
#data 2

f = open("./Statistics1-data/correlation2.txt", "r")
lines = f.readlines()
f.close()

x = []
y = []

for line in lines:
    (now_x, now_y) = line.replace("\n", "").split(",")
    x.append(float(now_x))
    y.append(float(now_y))

In [6]:
np.corrcoef(x, y)

array([[ 1.        , -0.67368751],
       [-0.67368751,  1.        ]])

In [7]:
# -0.67368751

In [8]:
#data 3

f = open("./Statistics1-data/correlation3.txt", "r")
lines = f.readlines()
f.close()

x = []
y = []

for line in lines:
    (now_x, now_y) = line.replace("\n", "").split(",")
    x.append(float(now_x))
    y.append(float(now_y))

In [9]:
np.corrcoef(x, y)

array([[1.        , 0.03691201],
       [0.03691201, 1.        ]])

In [10]:
# 0.03691201

In [11]:
#data 4

f = open("./Statistics1-data/correlation4.txt", "r")
lines = f.readlines()
f.close()

x = []
y = []

for line in lines:
    (now_x, now_y) = line.replace("\n", "").split(",")
    x.append(float(now_x))
    y.append(float(now_y))

In [12]:
np.corrcoef(x, y)

array([[ 1.        , -0.04976285],
       [-0.04976285,  1.        ]])

In [13]:
# -0.04976285